# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "14:05"
      timezone: "America/New_York"
  - package-ecosystem: "docker-compose"
    directories:
      - "/hosts/*/*"
    ignore:
      - dependency-name: "caddy-*" 
    schedule:
      interval: "daily"
      time: "11:30"
      timezone: "America/New_York"
  - package-ecosystem: "docker"
    directories:
      - "/Dockerfiles/*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:35"
      timezone: "America/New_York"