networks:
  caddy-net:
    name: caddy_caddy-net
    external: true

services:
  speedtest:
    container_name: speedtest
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DISPLAY_TIMEZONE=${DISPLAY_TIMEZONE}
      - PGID=${PGID}
      - PRUNE_RESULTS_OLDER_THAN=${PRUNE_RESULTS_OLDER_THAN}
      - PUID=${PUID}
      - SPEEDTEST_SCHEDULE=${SPEEDTEST_SCHEDULE}
      - SPEEDTEST_SERVERS=${SPEEDTEST_SERVERS}
      - TZ=${TZ}
    expose:
      - 80
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost/api/healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    hostname: speedtest
    image: linuxserver/speedtest-tracker:v1.13.10-ls138
    labels:
      - 'wud.display.icon=sh:speedtest-tracker'
      - 'wud.tag.include=^v\d+\.\d+\.\d+.*$$'
      - 'wud.link.template=https://github.com/linuxserver/docker-speedtest-tracker/releases/tag/v$${raw}'
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
    networks:
      caddy-net:
    restart: unless-stopped
    volumes:
      - data:/config

volumes:
  data:
