networks:
  caddy-net:
    name: caddy_caddy-net
    external: true

services:
  pairdrop:
    container_name: pairdrop
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - DEBUG_MODE=${DEBUG_MODE}
      - PGID=${PGID}
      - PUID=${PUID}
      - RATE_LIMIT=${RATE_LIMIT}
      - TZ=${TZ}
      - WS_FALLBACK=${WS_FALLBACK}
    expose:
      - 3000
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --no-verbose http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    hostname: pairdrop
    image: linuxserver/pairdrop:v1.11.2-ls132
    labels:
      - 'wud.display.icon=sh:pairdrop'
      - 'wud.tag.include=^v\d+\.\d+\.\d+.*$$'
      - 'wud.link.template=https://github.com/linuxserver/docker-pairdrop/releases/tag/$${raw}'
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
    networks:
      caddy-net:
    read_only: true
    restart: unless-stopped
    tmpfs:
      - /run:exec
