networks:
  caddy-net:
    name: caddy-net
    external: true

services:
  drawio:
    container_name: drawio
    dns: 172.19.0.2
    deploy:
      resources:
        limits:
          memory: 256M
    expose:
      - 8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    hostname: drawio
    image: jgraph/drawio:29.3.6
    labels:
      - 'wud.display.icon=sh:draw-io'
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'
      - 'wud.link.template=https://github.com/jgraph/drawio/releases/tag/v$${major}.$${minor}.$${patch}'
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
    networks:
      caddy-net:
        ipv4_address: 172.19.0.22
    restart: unless-stopped
