networks:
  pihole-net:
    name: pihole_docker_pihole-net
    external: true

services:
  homer:
    container_name: homer
    deploy:
      resources:
        limits:
          memory: 64M
    environment:
      - INIT_ASSETS=${INIT_ASSETS}
    expose:
      - 8080
    hostname: homer
    image: b4bz/homer:v25.11.1
    labels:
      - 'wud.display.icon=sh:homer'
      - 'wud.tag.include=^v?\d+(?:\.\d{1,2})?\.\d+$$'
      - 'wud.link.template=https://github.com/bastienwirtz/homer/releases/tag/$${raw}'
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
    networks:
      pihole-net:
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - assets:/www/assets

volumes:
  assets:
