networks:
  caddy-net:
    name: caddy-net
    external: true

services:
  pihole-gmkg3:
    container_name: pihole-gmkg3
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - FTLCONF_LOCAL_IPV4=${FTLCONF_LOCAL_IPV4}
      - FTLCONF_dns_bogusPriv=${FTLCONF_dns_bogusPriv}
      - FTLCONF_dns_dnssec=${FTLCONF_dns_dnssec}
      - FTLCONF_dns_domainNeeded=${FTLCONF_dns_domainNeeded}
      - FTLCONF_dns_listeningMode=${FTLCONF_dns_listeningMode}
      - FTLCONF_dns_upstreams=${FTLCONF_dns_upstreams}
      - FTLCONF_webserver_api_password=${FTLCONF_webserver_api_password}
      - TZ=${TZ}
    expose:
      - 80
    hostname: pihole-gmkg3
    image: pihole/pihole:2026.02.0
    labels:
      - 'wud.display.icon=sh:pi-hole'
      - 'wud.tag.include=^\d+(?:\.\d{1,2})?\.\d+$$'
      - 'wud.link.template=https://github.com/pi-hole/docker-pi-hole/releases/tag/$${raw}'
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
    networks:
      caddy-net:
        ipv4_address: 172.18.0.2
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: unless-stopped
    volumes:
      - etc-pihole:/etc/pihole
      - etc-dnsmasqd:/etc/dnsmasq.d


  unbound:
    container_name: unbound
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ['CMD', 'drill-hc', '@127.0.0.1', 'dnssec.works']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    hostname: unbound
    image: klutchell/unbound:1.24.2
    labels:
      - 'wud.display.icon=sh:unbound'
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'
      - 'wud.link.template=https://github.com/klutchell/unbound-docker/releases/tag/v$${major}.$${minor}.$${patch}'
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
    networks:
      caddy-net:
        ipv4_address: 172.18.0.3
    restart: unless-stopped
    volumes:
      - unbound-config:/opt/unbound/etc/unbound


volumes:
  etc-pihole:
  etc-dnsmasqd:
  unbound-config:
