# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
networks:
  pihole-net:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1

services:
  pihole:
    container_name: pihole-rpi4
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - FTLCONF_LOCAL_IPV4=${FTLCONF_LOCAL_IPV4}
      - FTLCONF_dns_bogusPriv=${FTLCONF_dns_bogusPriv}
      - FTLCONF_dns_dnssec=${FTLCONF_dns_dnssec}
      - FTLCONF_dns_domainNeeded=${FTLCONF_dns_domainNeeded}
      - FTLCONF_dns_listeningMode=${FTLCONF_dns_listeningMode}
      - FTLCONF_dns_upstreams=${FTLCONF_dns_upstreams}
      - FTLCONF_webserver_api_password=${FTLCONF_webserver_api_password}
      - TZ=${TZ}
    expose:
      - 80
    hostname: pihole-rpi4
    image: pihole/pihole:2026.02.0
    labels:
      - 'wud.display.icon=sh:pi-hole'
      - 'wud.tag.include=^\d+(?:\.\d{1,2})?\.\d+$$'
      - 'wud.link.template=https://github.com/pi-hole/docker-pi-hole/releases/tag/$${raw}'
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
    networks:
      pihole-net:
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Pi-hole as DHCP server
    restart: unless-stopped
    volumes:
      - etc-pihole:/etc/pihole
      - etc-dnsmasqd:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
      # - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed


  unbound:
    container_name: unbound
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      # Use the drill wrapper binary to reduce the exit codes to 0 or 1 for healthchecks
      test: ['CMD', 'drill-hc', '@127.0.0.1', 'dnssec.works']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    hostname: unbound
    image: klutchell/unbound:1.24.2
    labels:
      - 'wud.display.icon=sh:unbound'
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'
      - 'wud.link.template=https://github.com/klutchell/unbound-docker/releases/tag/v$${major}.$${minor}.$${patch}'
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
    networks:
      pihole-net:
    restart: unless-stopped
    volumes:
      - unbound-config:/opt/unbound/etc/unbound


volumes:
  etc-pihole:
  etc-dnsmasqd:
  unbound-config:
