networks:
  caddy-net:
    name: caddy-net
    external: true

services:
  vaultwarden:
    container_name: vaultwarden
    deploy:
      resources:
        limits:
          memory: 256M
    dns: 172.18.0.2
    environment:
      - DOMAIN=${DOMAIN}
    expose:
      - 80
    hostname: vaultwarden
    image: vaultwarden/server:1.35.3-alpine
    labels:
      - 'wud.display.icon=sh:vaultwarden'
      - 'wud.tag.include=^\d+\.\d+\.\d+-alpine'
      - 'wud.link.template=https://github.com/dani-garcia/vaultwarden/releases/tag/$${major}.$${minor}.$${patch}'
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
    networks:
      caddy-net:
        ipv4_address: 172.18.0.21
    restart: unless-stopped
    volumes:
      - data:/data/

volumes:
  data:
